import { createFileRoute } from "@tanstack/react-router";
import { useRef, useState } from "react";
import AppShell from "@/components/AppShell";
import { sampleChild, vaccineSchedule } from "@/lib/mockData";
import { Download, MessageCircle } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/report")({ component: Report });

function Report() {
  const [lang, setLang] = useState<"en" | "uz" | "ru">("en");
  const [notes, setNotes] = useState("");
  const ref = useRef<HTMLDivElement>(null);

  const handleDownload = async () => {
    if (!ref.current) return;
    const html2pdf = (await import("html2pdf.js")).default;
    await html2pdf().from(ref.current).set({
      margin: 12,
      filename: `Yasha-Report-${sampleChild.name}.pdf`,
      html2canvas: { scale: 2 },
      jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
    }).save();
    toast.success("Ready! ✓");
  };

  const handleWhatsApp = () => {
    const summary = `*Yasha Health Report — ${sampleChild.name}*\n` +
      `DOB: ${sampleChild.dob}\n` +
      `Height: ${sampleChild.heightCm} cm, Weight: ${sampleChild.weightKg} kg\n` +
      `BMI: ${(sampleChild.weightKg / Math.pow(sampleChild.heightCm / 100, 2)).toFixed(1)}\n` +
      `Vaccines: ${vaccineSchedule.filter(v => v.done).length}/${vaccineSchedule.length} complete\n` +
      (notes ? `Notes: ${notes}\n` : "") +
      `\nGenerated by Yasha App`;
    const url = `https://wa.me/?text=${encodeURIComponent(summary)}`;
    window.open(url, "_blank");
  };

  const labels = {
    en: { title: "Family Health Report", profile: "Child profile", growth: "Growth", nutr: "Nutrition (7-day avg)", screen: "Screen time (weekly avg)", vac: "Vaccinations", notes: "Parent notes" },
    uz: { title: "Oilaviy sog'liq hisoboti", profile: "Bola profili", growth: "O'sish", nutr: "Ovqatlanish (7 kunlik o'rtacha)", screen: "Ekran vaqti (haftalik o'rtacha)", vac: "Emlash", notes: "Ota-ona izohlari" },
    ru: { title: "Семейный отчёт о здоровье", profile: "Профиль ребёнка", growth: "Рост", nutr: "Питание (среднее за 7 дней)", screen: "Экранное время (за неделю)", vac: "Прививки", notes: "Заметки родителя" },
  }[lang];

  return (
    <AppShell>
      <div className="max-w-3xl mx-auto px-4 py-8 space-y-6">
        <header className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h1 className="text-3xl font-bold">Doctor PDF report</h1>
            <p className="text-muted-foreground mt-1">Auto-compiled. Print-ready.</p>
          </div>
          <div className="flex items-center gap-2">
            <select value={lang} onChange={(e) => setLang(e.target.value as never)} className="min-h-11 px-3 rounded-xl border border-input bg-background">
              <option value="en">English</option>
              <option value="uz">O'zbekcha</option>
              <option value="ru">Русский</option>
            </select>
            <button onClick={handleDownload} className="min-h-11 px-4 rounded-xl bg-primary text-primary-foreground font-medium hover:bg-primary-dark inline-flex items-center gap-2">
              <Download className="w-4 h-4" /> PDF
            </button>
            <button onClick={handleWhatsApp} className="min-h-11 px-4 rounded-xl bg-[#25D366] text-white font-medium hover:opacity-90 inline-flex items-center gap-2">
              <MessageCircle className="w-4 h-4" /> WhatsApp
            </button>
          </div>
        </header>

        <div className="yasha-card p-5">
          <label className="text-sm font-medium">{labels.notes}</label>
          <textarea
            value={notes} onChange={(e) => setNotes(e.target.value)}
            rows={3}
            placeholder="Add any concerns or context for the doctor…"
            className="mt-2 w-full p-3 rounded-xl border border-input bg-background"
          />
        </div>

        {/* Print area */}
        <div ref={ref} className="bg-white text-black rounded-2xl shadow-md p-8 print:shadow-none" style={{ fontFamily: "Inter, sans-serif" }}>
          <div className="border-b border-gray-300 pb-4 mb-6 flex justify-between items-end">
            <div>
              <h2 className="text-2xl font-bold">{labels.title}</h2>
              <p className="text-xs text-gray-600 mt-1">Generated by Yasha App · {new Date().toLocaleDateString()}</p>
            </div>
            <span className="text-orange-600 font-bold text-xl">Yasha</span>
          </div>

          <Section title={labels.profile}>
            <KV k="Name" v={sampleChild.name} />
            <KV k="Date of birth" v={sampleChild.dob} />
            <KV k="Sex" v={sampleChild.sex} />
          </Section>

          <Section title={labels.growth}>
            <KV k="Height" v={`${sampleChild.heightCm} cm`} />
            <KV k="Weight" v={`${sampleChild.weightKg} kg`} />
            <KV k="BMI" v={(sampleChild.weightKg / Math.pow(sampleChild.heightCm / 100, 2)).toFixed(1)} />
            <KV k="Percentile band" v="50th (healthy)" />
          </Section>

          <Section title={labels.nutr}>
            <KV k="Iron" v="7.2 / 10 mg" />
            <KV k="Calcium" v="640 / 800 mg" />
            <KV k="Vitamin D" v="180 / 600 IU (low)" />
            <KV k="Zinc" v="4.4 / 5 mg" />
            <KV k="Protein" v="22 / 19 g ✓" />
          </Section>

          <Section title={labels.screen}>
            <KV k="Avg daily screen" v="2.1 h" />
            <KV k="Avg outdoor time" v="1.0 h" />
            <KV k="20-20-20 streak" v="4 days" />
          </Section>

          <Section title={labels.vac}>
            <ul className="text-sm space-y-1">
              {vaccineSchedule.map((v) => (
                <li key={v.name} className="flex justify-between border-b border-dashed border-gray-200 py-1">
                  <span>{v.name} <span className="text-gray-500">({v.due})</span></span>
                  <span className={v.done ? "text-green-700" : "text-amber-700"}>
                    {v.done ? `✓ ${v.doneDate}` : "Pending"}
                  </span>
                </li>
              ))}
            </ul>
          </Section>

          {notes && (
            <Section title={labels.notes}>
              <p className="text-sm whitespace-pre-wrap">{notes}</p>
            </Section>
          )}

          <p className="text-[10px] text-gray-500 border-t border-gray-300 pt-3 mt-6">
            Yasha App provides health information only. It is not a substitute for medical advice, diagnosis, or treatment.
          </p>
        </div>
      </div>
    </AppShell>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-5">
      <h3 className="text-sm font-bold uppercase tracking-wider text-gray-700 mb-2">{title}</h3>
      <div className="text-sm">{children}</div>
    </div>
  );
}
function KV({ k, v }: { k: string; v: string | number }) {
  return (
    <div className="flex justify-between py-1 border-b border-dashed border-gray-200">
      <span className="text-gray-600">{k}</span>
      <span className="font-medium">{v}</span>
    </div>
  );
}
