/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaccinationRouteImport } from './routes/vaccination'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScreenHealthRouteImport } from './routes/screen-health'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as ExerciseRouteImport } from './routes/exercise'
import { Route as DeficiencyRouteImport } from './routes/deficiency'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'

const VaccinationRoute = VaccinationRouteImport.update({
  id: '/vaccination',
  path: '/vaccination',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenHealthRoute = ScreenHealthRouteImport.update({
  id: '/screen-health',
  path: '/screen-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseRoute = ExerciseRouteImport.update({
  id: '/exercise',
  path: '/exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const DeficiencyRoute = DeficiencyRouteImport.update({
  id: '/deficiency',
  path: '/deficiency',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/deficiency': typeof DeficiencyRoute
  '/exercise': typeof ExerciseRoute
  '/growth': typeof GrowthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mood': typeof MoodRoute
  '/nutrition': typeof NutritionRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/screen-health': typeof ScreenHealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sleep': typeof SleepRoute
  '/vaccination': typeof VaccinationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/deficiency': typeof DeficiencyRoute
  '/exercise': typeof ExerciseRoute
  '/growth': typeof GrowthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mood': typeof MoodRoute
  '/nutrition': typeof NutritionRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/screen-health': typeof ScreenHealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sleep': typeof SleepRoute
  '/vaccination': typeof VaccinationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/deficiency': typeof DeficiencyRoute
  '/exercise': typeof ExerciseRoute
  '/growth': typeof GrowthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mood': typeof MoodRoute
  '/nutrition': typeof NutritionRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/screen-health': typeof ScreenHealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sleep': typeof SleepRoute
  '/vaccination': typeof VaccinationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/deficiency'
    | '/exercise'
    | '/growth'
    | '/leaderboard'
    | '/login'
    | '/mood'
    | '/nutrition'
    | '/register'
    | '/report'
    | '/screen-health'
    | '/sitemap.xml'
    | '/sleep'
    | '/vaccination'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/deficiency'
    | '/exercise'
    | '/growth'
    | '/leaderboard'
    | '/login'
    | '/mood'
    | '/nutrition'
    | '/register'
    | '/report'
    | '/screen-health'
    | '/sitemap.xml'
    | '/sleep'
    | '/vaccination'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/deficiency'
    | '/exercise'
    | '/growth'
    | '/leaderboard'
    | '/login'
    | '/mood'
    | '/nutrition'
    | '/register'
    | '/report'
    | '/screen-health'
    | '/sitemap.xml'
    | '/sleep'
    | '/vaccination'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  DashboardRoute: typeof DashboardRoute
  DeficiencyRoute: typeof DeficiencyRoute
  ExerciseRoute: typeof ExerciseRoute
  GrowthRoute: typeof GrowthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MoodRoute: typeof MoodRoute
  NutritionRoute: typeof NutritionRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  ScreenHealthRoute: typeof ScreenHealthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SleepRoute: typeof SleepRoute
  VaccinationRoute: typeof VaccinationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vaccination': {
      id: '/vaccination'
      path: '/vaccination'
      fullPath: '/vaccination'
      preLoaderRoute: typeof VaccinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-health': {
      id: '/screen-health'
      path: '/screen-health'
      fullPath: '/screen-health'
      preLoaderRoute: typeof ScreenHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise': {
      id: '/exercise'
      path: '/exercise'
      fullPath: '/exercise'
      preLoaderRoute: typeof ExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deficiency': {
      id: '/deficiency'
      path: '/deficiency'
      fullPath: '/deficiency'
      preLoaderRoute: typeof DeficiencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  DashboardRoute: DashboardRoute,
  DeficiencyRoute: DeficiencyRoute,
  ExerciseRoute: ExerciseRoute,
  GrowthRoute: GrowthRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MoodRoute: MoodRoute,
  NutritionRoute: NutritionRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  ScreenHealthRoute: ScreenHealthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SleepRoute: SleepRoute,
  VaccinationRoute: VaccinationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
